Fix typo in `DirectionalHint` Callout type
microsoft/fluentui-react-native pull request #3648
Opened 2024-06-07 21:02 UTC by lawrencewin

### Platforms Impacted
- [ ] iOS
- [x] macOS
- [x] win32 (Office)
- [ ] windows
- [ ] android

### Description of changes

There's a typo in the `DirectionalHint` type for Callout's `directionalHint` prop, where `"bottomLeftEdge"` is spelled as `"bottonLeftEdge"`. This PR fixes this so the linter stops crying. 

### Pull request checklist

This PR has considered (when applicable):
- [ ] Automated Tests
- [ ] Documentation and examples
- [ ] Keyboard Accessibility
- [ ] Voiceover
- [ ] Internationalization and Right-to-left Layouts

2024-06-07 21:11 UTC, PPatBoyd approved these changes, later dismissed

2024-06-07 21:21 UTC, amgleitman approved these changes, later dismissed

2024-06-07 21:28 UTC, Saadnajmi requested changes
You'll have to update this too: https://github.com/microsoft/fluentui-react-native/blob/main/packages/components/Callout/macos/FRNCalloutManager.m#L18-L33

2024-06-07 21:28 UTC, Saadnajmi commented
Which.. after that, we'll have to ensure that the change makes it internally and doesn't cause regressions for partners who don't update their bundles..

2024-06-10 17:28 UTC, PPatBoyd commented
> Which.. after that, we'll have to ensure that the change makes it internally and doesn't cause regressions for partners who don't update their bundles..

FWIW there are no current users of the enum value that I could find in any Office repos

2026-08-20 00:16 UTC, closed without merging